spring.application.name=placement-management-system

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/placement_management
spring.datasource.username=root
spring.datasource.password=CampusConnect@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true